application_name: Rust OPC-UA Sample Server
application_uri: urn:RustOpcUa:SampleServer
product_uri: urn:RustOpcUa:SampleServer
create_sample_keypair: true
certificate_path: own/cert.der
private_key_path: own/private.pem
pki_dir: pki
discovery_server_url: opc.tcp://localhost:4840/UADiscovery
endpoints:
  none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 0
    password_security_policy: ~
    user_token_ids:
      - anonymous
user_tokens:
  anonymous:
    user: ~
    pass: ~
discovery_urls:
  - opc.tcp://127.0.0.1:4855/
tcp_config:
  hello_timeout: 120
  host: 0.0.0.0
  port: 4855
limits:
  clients_can_modify_address_space: false
  max_array_length: 65536
  max_byte_string_length: 65536
  max_chunk_count: 128
  max_chunk_size: 65536
  max_connections: 100
  max_message_size: 2097152
  max_string_length: 65536
  max_subscriptions: 100
  receive_buffer_size: 65536
  send_buffer_size: 65536
performance:
  single_threaded_executor: false
