[package]
name = "async-opcua-mqtt-client"
version = "0.13.0"
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2021"

[dependencies]
pico-args = "0.5"
rumqttc = "0.23"
tokio = { workspace = true }

[dependencies.async-opcua]
path = "../../async-opcua"
features = ["client", "console-logging"]
