[package]
name = "async-opcua-certificate-creator"
version = "0.13.0"
description = "OPC UA certificate creator"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/freeopcua/async-opcua"
license = "MPL-2.0"
keywords = ["opcua", "opc", "ua"]
categories = ["embedded", "network-programming"]
edition = "2021"

[dependencies]
pico-args = "0.5"

[dependencies.async-opcua]
path = "../../async-opcua"
