[package]
name = "opcua-chess-server"
version = "0.13.0"
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { workspace = true }
uci = "0.1.1"

[dependencies.opcua]
path = "../../lib"
features = ["server", "console-logging"]
