[package]
name = "async-opcua-chess-server"
version = "0.13.0"
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { workspace = true }
uci = "0.1.1"

[dependencies.async-opcua]
path = "../../async-opcua"
features = ["server", "console-logging"]
