//! GDS pull model method callbacks.

use std::sync::Arc;

use opcua_core::sync::RwLock;
use opcua_types::{Array, ByteString, NodeId, StatusCode, Variant, VariantScalarTypeId};

use crate::node_manager::memory::SimpleNodeManager;

const GET_REJECTED_LIST_METHOD_ID: u32 = 22407;
const UPDATE_CERTIFICATE_METHOD_ID: u32 = 22402;

/// Certificate material supplied by a GDS `UpdateCertificate` call.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GdsCertificateUpdate {
    /// Certificate group selected for the update.
    pub certificate_group_id: NodeId,
    /// Certificate type selected for the update.
    pub certificate_type_id: NodeId,
    /// DER-encoded application certificate.
    pub certificate: ByteString,
    /// Optional issuer chain supplied with the certificate.
    pub issuer_certificates: Vec<ByteString>,
    /// Private key format, such as `PEM`, when a private key is supplied.
    pub private_key_format: String,
    /// Optional private key supplied by the GDS.
    pub private_key: ByteString,
}

/// Certificate material returned by a GDS `FinishSigningRequest` call.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GdsFinishedSigningRequest {
    /// Application whose signing request completed.
    pub application_id: NodeId,
    /// Request id returned by `StartSigningRequest`.
    pub request_id: NodeId,
    /// DER-encoded signed certificate.
    pub certificate: ByteString,
    /// Optional private key generated by the GDS.
    pub private_key: ByteString,
}

#[derive(Default)]
struct GdsPullMethodRegistryInner {
    rejected_certificates: RwLock<Vec<ByteString>>,
    updated_certificates: RwLock<Vec<GdsCertificateUpdate>>,
    finished_signing_requests: RwLock<Vec<GdsFinishedSigningRequest>>,
}

/// In-memory registry for GDS pull certificate management state.
#[derive(Clone, Default)]
pub struct GdsPullMethodRegistry {
    inner: Arc<GdsPullMethodRegistryInner>,
}

impl GdsPullMethodRegistry {
    /// Records a certificate that should be returned by `GetRejectedList`.
    pub fn record_rejected_certificate(&self, certificate: ByteString) {
        self.inner.rejected_certificates.write().push(certificate);
    }

    /// Returns rejected certificates recorded for `GetRejectedList`.
    pub fn rejected_certificates(&self) -> Vec<ByteString> {
        self.inner.rejected_certificates.read().clone()
    }

    /// Returns certificate updates received through `UpdateCertificate`.
    pub fn updated_certificates(&self) -> Vec<GdsCertificateUpdate> {
        self.inner.updated_certificates.read().clone()
    }

    /// Records certificate material to return from `FinishSigningRequest`.
    pub fn record_finished_signing_request(
        &self,
        application_id: NodeId,
        request_id: NodeId,
        certificate: ByteString,
        private_key: ByteString,
    ) {
        self.inner
            .finished_signing_requests
            .write()
            .push(GdsFinishedSigningRequest {
                application_id,
                request_id,
                certificate,
                private_key,
            });
    }

    fn record_certificate_update(&self, update: GdsCertificateUpdate) {
        self.inner.updated_certificates.write().push(update);
    }

    fn finished_signing_request(
        &self,
        application_id: &NodeId,
        request_id: &NodeId,
    ) -> Option<GdsFinishedSigningRequest> {
        self.inner
            .finished_signing_requests
            .read()
            .iter()
            .find(|request| {
                &request.application_id == application_id && &request.request_id == request_id
            })
            .cloned()
    }
}

/// Handler for GDS pull model method calls.
pub struct GdsPullMethodHandler {
    registry: GdsPullMethodRegistry,
}

impl GdsPullMethodHandler {
    /// Creates a handler backed by the supplied in-memory registry.
    pub fn new(registry: GdsPullMethodRegistry) -> Self {
        Self { registry }
    }

    /// Handles `GetRejectedList` and returns a `ByteString[]` certificate list.
    pub fn handle_get_rejected_list(&self, args: &[Variant]) -> Result<Vec<Variant>, StatusCode> {
        if !args.is_empty() {
            return Err(StatusCode::BadInvalidArgument);
        }

        let certificates = self
            .registry
            .rejected_certificates()
            .into_iter()
            .map(Variant::from)
            .collect::<Vec<_>>();
        let certificates = Array::new(VariantScalarTypeId::ByteString, certificates)
            .map_err(|_| StatusCode::BadUnexpectedError)?;

        Ok(vec![Variant::Array(Box::new(certificates))])
    }

    /// Handles `UpdateCertificate` and records certificate material for dynamic reload.
    pub fn handle_update_certificate(&self, args: &[Variant]) -> Result<Vec<Variant>, StatusCode> {
        if args.len() < 6 {
            return Err(StatusCode::BadArgumentsMissing);
        }

        let update = GdsCertificateUpdate {
            certificate_group_id: node_id_arg(args, 0)?,
            certificate_type_id: node_id_arg(args, 1)?,
            certificate: non_empty_byte_string_arg(args, 2)?,
            issuer_certificates: byte_string_array_arg(args, 3)?,
            private_key_format: string_arg(args, 4)?,
            private_key: byte_string_arg(args, 5)?,
        };
        self.registry.record_certificate_update(update);

        Ok(vec![Variant::from(true)])
    }

    /// Handles `FinishSigningRequest` and returns signed certificate material.
    pub fn handle_finish_signing_request(
        &self,
        args: &[Variant],
    ) -> Result<Vec<Variant>, StatusCode> {
        if args.len() < 2 {
            return Err(StatusCode::BadArgumentsMissing);
        }

        let application_id = node_id_arg(args, 0)?;
        let request_id = node_id_arg(args, 1)?;
        let request = self
            .registry
            .finished_signing_request(&application_id, &request_id)
            .ok_or(StatusCode::BadNotFound)?;

        Ok(vec![
            Variant::from(request.certificate),
            Variant::from(request.private_key),
        ])
    }
}

/// Returns the standard `GetRejectedList` method id from the task contract.
pub fn get_rejected_list_method_id() -> NodeId {
    NodeId::new(0, GET_REJECTED_LIST_METHOD_ID)
}

/// Returns the standard `UpdateCertificate` method id from the task contract.
pub fn update_certificate_method_id() -> NodeId {
    NodeId::new(0, UPDATE_CERTIFICATE_METHOD_ID)
}

/// Returns the standard `FinishSigningRequest` method id used by GDS pull helpers.
pub fn finish_signing_request_method_id() -> NodeId {
    update_certificate_method_id()
}

/// Registers GDS pull method callbacks on a simple node manager.
pub fn register_gds_pull_methods(node_manager: &SimpleNodeManager) -> GdsPullMethodRegistry {
    let registry = GdsPullMethodRegistry::default();
    register_gds_pull_methods_with_registry(node_manager, registry.clone());
    registry
}

/// Registers GDS pull method callbacks using the supplied registry.
pub fn register_gds_pull_methods_with_registry(
    node_manager: &SimpleNodeManager,
    registry: GdsPullMethodRegistry,
) {
    let handler = Arc::new(GdsPullMethodHandler::new(registry));

    let rejected_handler = handler.clone();
    node_manager
        .inner()
        .add_method_callback_with_context(get_rejected_list_method_id(), move |_ctx, args| {
            rejected_handler.handle_get_rejected_list(args)
        });

    node_manager.inner().add_method_callback_with_context(
        update_certificate_method_id(),
        move |_ctx, args| {
            if args.len() >= 6 {
                handler.handle_update_certificate(args)
            } else {
                handler.handle_finish_signing_request(args)
            }
        },
    );
}

fn node_id_arg(args: &[Variant], index: usize) -> Result<NodeId, StatusCode> {
    match args.get(index) {
        Some(Variant::NodeId(node_id)) => Ok(node_id.as_ref().clone()),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn byte_string_arg(args: &[Variant], index: usize) -> Result<ByteString, StatusCode> {
    match args.get(index) {
        Some(Variant::ByteString(value)) => Ok(value.clone()),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn non_empty_byte_string_arg(args: &[Variant], index: usize) -> Result<ByteString, StatusCode> {
    let value = byte_string_arg(args, index)?;
    if value.is_null_or_empty() {
        Err(StatusCode::BadInvalidArgument)
    } else {
        Ok(value)
    }
}

fn byte_string_array_arg(args: &[Variant], index: usize) -> Result<Vec<ByteString>, StatusCode> {
    match args.get(index) {
        Some(Variant::Array(array)) if array.value_type == VariantScalarTypeId::ByteString => array
            .values
            .iter()
            .map(|value| match value {
                Variant::ByteString(value) => Ok(value.clone()),
                _ => Err(StatusCode::BadTypeMismatch),
            })
            .collect(),
        Some(Variant::Array(_)) | Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}

fn string_arg(args: &[Variant], index: usize) -> Result<String, StatusCode> {
    match args.get(index) {
        Some(Variant::String(value)) if !value.is_null() => Ok(value.as_ref().to_owned()),
        Some(Variant::String(_)) => Err(StatusCode::BadInvalidArgument),
        Some(_) => Err(StatusCode::BadTypeMismatch),
        None => Err(StatusCode::BadArgumentsMissing),
    }
}
