[package]
name = "opcua-event-client"
version = "0.13.0"
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2021"

[dependencies]
pico-args = "0.5"
tokio = { workspace = true }

[dependencies.opcua]
path = "../../lib"
features = ["client", "console-logging"]
